from enum import StrEnum


class RiskType(StrEnum):
    """What kind of revenue is at risk."""
    PAYMENT_FAILURE = "PAYMENT_FAILURE"
    CHECKOUT_ABANDONMENT = "CHECKOUT_ABANDONMENT"
    SUBSCRIPTION_FAILURE = "SUBSCRIPTION_FAILURE"
    OVERDUE_INVOICE = "OVERDUE_INVOICE"


class FailureReason(StrEnum):
    UPI_TIMEOUT = "UPI_TIMEOUT"
    CARD_DECLINED = "CARD_DECLINED"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    EXPIRED_CARD = "EXPIRED_CARD"
    USER_ABANDONED = "USER_ABANDONED"
    PRICE_OBJECTION = "PRICE_OBJECTION"
    PRODUCT_UNCERTAINTY = "PRODUCT_UNCERTAINTY"
    TECHNICAL_ERROR = "TECHNICAL_ERROR"
    PAYMENT_OVERDUE = "PAYMENT_OVERDUE"
    UNKNOWN = "UNKNOWN"


class CaseState(StrEnum):
    """Deterministic state machine. The LLM never sets these directly."""
    DETECTED = "DETECTED"
    ANALYZING = "ANALYZING"
    STRATEGY_SELECTED = "STRATEGY_SELECTED"
    AWAITING_ACTION = "AWAITING_ACTION"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    CUSTOMER_RESPONDED = "CUSTOMER_RESPONDED"
    RECOVERED = "RECOVERED"
    ACTION_FAILED = "ACTION_FAILED"
    ESCALATED = "ESCALATED"
    EXPIRED = "EXPIRED"
    NO_RECOVERY = "NO_RECOVERY"


class Strategy(StrEnum):
    RETRY_PAYMENT = "RETRY_PAYMENT"
    PAYMENT_LINK = "PAYMENT_LINK"
    ANSWER_OBJECTION = "ANSWER_OBJECTION"
    INCENTIVE = "INCENTIVE"
    REMINDER = "REMINDER"
    PAYMENT_METHOD_UPDATE = "PAYMENT_METHOD_UPDATE"
    ESCALATE_HUMAN = "ESCALATE_HUMAN"
    DO_NOT_CONTACT = "DO_NOT_CONTACT"


class CustomerSegment(StrEnum):
    NEW = "NEW"
    RETURNING = "RETURNING"
    LOYAL = "LOYAL"
    VIP = "VIP"


class PolicyDecision(StrEnum):
    AUTO_ALLOWED = "AUTO_ALLOWED"
    REQUIRES_APPROVAL = "REQUIRES_APPROVAL"
    BLOCKED = "BLOCKED"


# Legal state transitions. Anything not listed here is rejected at runtime.
ALLOWED_TRANSITIONS: dict[CaseState, set[CaseState]] = {
    CaseState.DETECTED: {CaseState.ANALYZING, CaseState.EXPIRED},
    CaseState.ANALYZING: {CaseState.STRATEGY_SELECTED, CaseState.ESCALATED, CaseState.NO_RECOVERY},
    CaseState.STRATEGY_SELECTED: {CaseState.AWAITING_ACTION, CaseState.ESCALATED, CaseState.NO_RECOVERY},
    CaseState.AWAITING_ACTION: {CaseState.ACTION_EXECUTED, CaseState.ACTION_FAILED, CaseState.ESCALATED},
    CaseState.ACTION_EXECUTED: {CaseState.CUSTOMER_RESPONDED, CaseState.RECOVERED, CaseState.EXPIRED, CaseState.ESCALATED},
    CaseState.CUSTOMER_RESPONDED: {CaseState.RECOVERED, CaseState.AWAITING_ACTION, CaseState.ESCALATED, CaseState.NO_RECOVERY},
    CaseState.ACTION_FAILED: {CaseState.AWAITING_ACTION, CaseState.ESCALATED, CaseState.NO_RECOVERY},
    CaseState.RECOVERED: set(),
    CaseState.ESCALATED: {CaseState.RECOVERED, CaseState.NO_RECOVERY},
    CaseState.EXPIRED: set(),
    CaseState.NO_RECOVERY: set(),
}